# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b56357927d383b9fe1c007ba8ff5a0d69003e366485fa1f8fb0d60eb3300bfa1cf77ba79e09a00fbccba3d4ea3eee7dd33b7436e7fc8dfb533fd8b865cacde

test:
  secret_key_base: eaee8f4611019289e917a5676c1851d64254b4a21ea17f4c98441eaf2cb69982f202f8ccce318ca762c240c4cfe006b671f5fc587fd8ced363cbdecffa905a82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
